### ISSUE TITLE
CommandItem is not selectable with cmdk v1.0.0

### ISSUE THREAD

**Issue by adibmed** [BelkacemYerfa/shadcn-extension#51]
It appears you need to downgrade the 'cmdk' package to version 0.2.1 (in my case) for your project to work correctly.

**Comment by BelkacemYerfa** [comment]
Hi @adibmed 

Thanks for your feedback , yeah that's was an issue related to the shadcn command that we're using , since the component is built on top of it , we are forced to use the same version as shadcn's.

We can't give the fix on our version , since it will be a lot of stuff to setup for the end developer , especially without a CLI, still following this related [PR](https://github.com/shadcn-ui/ui/pull/3268) , as soon as it merges , we gonna provide it as the latest version .
