### ISSUE TITLE
[Feature]: Range slider with visual chart bars for values 

### ISSUE THREAD

**Issue by alamenai** [BelkacemYerfa/shadcn-extension#68]
Hi @BelkacemYerfa ,

When I was working on a new feature, my CTO asked me if we can make the  slider component as a range like this ( from Airbnb ):

![Screenshot from 2024-06-15 14-19-11](https://github.com/BelkacemYerfa/shadcn-extension/assets/20143684/622c89f3-1130-4c8e-9dca-1ad34f1b605b)

I don't know if your next release will include this component or no.

I have already opened a [new feature request](https://github.com/shadcn-ui/ui/issues/4008) in Shadcn project.

**Comment by BelkacemYerfa** [comment]
Hi @alamenai! Thanks for you suggestion.

There is 2 points are related to this component:
- First is that we have already set the component that will be added in the next release, so with that it is not going to be supported in the next release.
- Second as far as i see this component is very customisable for a very set of users, and since we're trying to make component that can be used globally, I don't see the benefit of having a component that is very custom for specific users.

Other than that i think it can be done using the Slider from shadcn-ui, check those [docs](https://ui.shadcn.com/docs/components/slider), if you have more control of it you can head to the radix primitive to check it out [here](https://ui.shadcn.com/docs/components/slider).

Other than that gonna talk to @gaurangrshah about this also and we can also hear his thoughts about it.

**Comment by gaurangrshah** [comment]
I like the idea, not sure if it's something we'd be including, but to get a better idea. @alamenai can you explain what type of data you're trying to visualize? Maybe if there is some universal utility to it we can create a more generalized version. 

We do have a discussion topic open in our roadmap for charting solutions, but that was before shadcn-ui added [recharts](https://recharts.org/en-US/). If we do build charting components they will also use recharts to ensure our users don't have to use 2 different libraries for the same solution.
