### ISSUE TITLE
How to attach a selection event listener to TreeView?

### ISSUE THREAD

**Issue by petervelosy** [BelkacemYerfa/shadcn-extension#69]
Maybe I am overseeing something, but I haven't found any onItemSelected() or similar callback on TreeView. How is it possible to react to the selection event? 

Thank you!

**Comment by BelkacemYerfa** [comment]
Hi @petervelosy! Thanks for your feedback.

Actually there is no selection event for the tree view you can just select the element and it works since it uses the accordion component from radix-ui package. And if you want a link just wrap the link element from nextJs inside of the File one and it will work properly.

Let me know if there is any other issue that you're facing. Btw we have a discord server if you want to join there you [go](https://discord.com/invite/HMcgHeZQ).
